name: Release Workflow

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: Windows
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install npm and semantic-release
        run: |
          npm install --save-dev semantic-release

      - name: Install Dependencies
        run: npm ci

      - name: Execute Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
